//! Golden parity test. Reads `training/native/parity/golden.json` (generated by
//! `training/native/parity/gen_golden.mjs` from the JS reference) and asserts the
//! native core reproduces every value byte-for-byte.
//!
//! Run with: `cargo test`

use std::path::PathBuf;

use blokus_selfplay::{
    action_size, apply_move, create_initial_state, decode_action, encode_action,
    encode_state_tensor, generate_legal_moves, orientation_count, pass_action, score_player,
    score_state, GameState, Move, StartId, StartPolicy, Status,
};
use serde::Deserialize;
use sha2::{Digest, Sha256};

// ---- golden.json schema (only the fields we assert) ----

#[derive(Debug, Deserialize)]
struct Golden {
    #[serde(rename = "boardSize")]
    board_size: usize,
    #[serde(rename = "orientationCount")]
    orientation_count: usize,
    #[serde(rename = "actionSize")]
    action_size: usize,
    #[serde(rename = "passAction")]
    pass_action: usize,
    #[serde(rename = "startPoints")]
    start_points: StartPoints,
    #[serde(rename = "initialLegalMoveCounts")]
    initial_legal_move_counts: InitialLegalMoveCounts,
    #[serde(rename = "actionRoundTrips")]
    action_round_trips: Vec<ActionRoundTrip>,
    #[serde(rename = "scoringSamples")]
    scoring_samples: ScoringSamples,
    #[serde(rename = "deterministicGames")]
    deterministic_games: Vec<DeterministicGame>,
}

#[derive(Debug, Deserialize)]
struct StartPoints {
    #[serde(rename = "A")]
    a: Point,
    #[serde(rename = "B")]
    b: Point,
}

#[derive(Debug, Deserialize)]
struct Point {
    x: usize,
    y: usize,
}

#[derive(Debug, Deserialize)]
struct InitialLegalMoveCounts {
    #[serde(rename = "chooseStart")]
    choose_start: usize,
    #[serde(rename = "fixedStart")]
    fixed_start: usize,
}

#[derive(Debug, Deserialize)]
struct ActionRoundTrip {
    action: usize,
    player: u8,
    decoded: DecodedMove,
    reencoded: usize,
}

#[derive(Debug, Deserialize)]
struct DecodedMove {
    kind: String,
    #[allow(dead_code)]
    player: u8,
    #[serde(rename = "pieceId")]
    piece_id: Option<String>,
    #[serde(rename = "orientationGlobalId")]
    orientation_global_id: Option<usize>,
    x: Option<usize>,
    y: Option<usize>,
}

#[derive(Debug, Deserialize)]
struct ScoringSamples {
    #[serde(rename = "blankFinishedP0")]
    blank_finished_p0: i32,
    #[serde(rename = "allPlacedLastI1")]
    all_placed_last_i1: i32,
    #[serde(rename = "allPlacedLastI2")]
    all_placed_last_i2: i32,
}

#[derive(Debug, Deserialize)]
struct DeterministicGame {
    #[serde(rename = "startPolicy")]
    start_policy: String,
    plies: usize,
    status: String,
    #[serde(rename = "finalScoreA")]
    final_score_a: i32,
    #[serde(rename = "finalScoreB")]
    final_score_b: i32,
    #[serde(rename = "finalBoardSha")]
    final_board_sha: String,
    positions: Vec<Position>,
}

#[derive(Debug, Deserialize)]
struct Position {
    ply: usize,
    turn: u32,
    #[serde(rename = "currentPlayer")]
    current_player: u8,
    #[serde(rename = "legalMoveCount")]
    legal_move_count: usize,
    #[serde(rename = "moveIndex")]
    move_index: usize,
    #[serde(rename = "selectedAction")]
    selected_action: usize,
    #[serde(rename = "boardSha")]
    board_sha: String,
    #[serde(rename = "stateShaCurrent")]
    state_sha_current: String,
    #[serde(rename = "scoreA")]
    score_a: i32,
    #[serde(rename = "scoreB")]
    score_b: i32,
}

// ---- canonical serialisations (must match gen_golden.mjs) ----

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut s = String::with_capacity(64);
    for b in digest {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

/// board byte: cell == EMPTY(-1) ? 0 : (cell + 1), row-major (index = y*14 + x).
fn board_bytes(state: &GameState) -> Vec<u8> {
    state
        .board
        .iter()
        .map(|&cell| if cell < 0 { 0u8 } else { (cell + 1) as u8 })
        .collect()
}

/// state bytes: Float32 little-endian, order = plane -> y -> x, for `player`.
fn state_bytes(state: &GameState, player: u8) -> Vec<u8> {
    let tensor = encode_state_tensor(state, player);
    let mut bytes = Vec::with_capacity(tensor.len() * 4);
    for v in tensor {
        bytes.extend_from_slice(&v.to_le_bytes());
    }
    bytes
}

fn parse_policy(s: &str) -> StartPolicy {
    StartPolicy::parse(s).unwrap_or_else(|| panic!("unknown start policy {s}"))
}

fn load_golden() -> Golden {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("../parity/golden.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("failed to parse golden.json")
}

#[test]
fn parity_constants() {
    let g = load_golden();
    assert_eq!(g.board_size, blokus_selfplay::BOARD_SIZE, "board size");
    assert_eq!(g.orientation_count, 91, "golden orientationCount");
    assert_eq!(orientation_count(), 91, "native orientation count");
    assert_eq!(g.orientation_count, orientation_count(), "orientation count");
    assert_eq!(g.action_size, 17837, "golden actionSize");
    assert_eq!(action_size(), g.action_size, "native action size");
    assert_eq!(g.pass_action, 17836, "golden passAction");
    assert_eq!(pass_action(), g.pass_action, "native pass action");
    assert_eq!((g.start_points.a.x, g.start_points.a.y), (4, 4), "start A");
    assert_eq!((g.start_points.b.x, g.start_points.b.y), (9, 9), "start B");
    assert_eq!(StartId::A.point(), (4, 4), "native start A");
    assert_eq!(StartId::B.point(), (9, 9), "native start B");
}

#[test]
fn parity_initial_legal_move_counts() {
    let g = load_golden();
    let choose = generate_legal_moves(&create_initial_state(StartPolicy::ChooseStart)).len();
    let fixed = generate_legal_moves(&create_initial_state(StartPolicy::FixedStart)).len();
    assert_eq!(g.initial_legal_move_counts.choose_start, 828, "golden chooseStart");
    assert_eq!(g.initial_legal_move_counts.fixed_start, 414, "golden fixedStart");
    assert_eq!(choose, g.initial_legal_move_counts.choose_start, "native chooseStart");
    assert_eq!(fixed, g.initial_legal_move_counts.fixed_start, "native fixedStart");
}

#[test]
fn parity_action_round_trips() {
    let g = load_golden();
    for entry in &g.action_round_trips {
        let decoded = decode_action(entry.action, entry.player);
        let reencoded = encode_action(&decoded);
        assert_eq!(reencoded, entry.reencoded, "reencoded for action {}", entry.action);
        assert_eq!(reencoded, entry.action, "round-trip for action {}", entry.action);

        match (&decoded, entry.decoded.kind.as_str()) {
            (Move::Pass { player }, "pass") => {
                assert_eq!(*player, entry.player, "pass player for action {}", entry.action);
            }
            (
                Move::Place {
                    piece_id,
                    orientation_global_id,
                    x,
                    y,
                    ..
                },
                "place",
            ) => {
                assert_eq!(
                    Some(piece_id),
                    entry.decoded.piece_id.as_ref(),
                    "pieceId for action {}",
                    entry.action
                );
                assert_eq!(
                    Some(*orientation_global_id),
                    entry.decoded.orientation_global_id,
                    "orientationGlobalId for action {}",
                    entry.action
                );
                assert_eq!(Some(*x), entry.decoded.x, "x for action {}", entry.action);
                assert_eq!(Some(*y), entry.decoded.y, "y for action {}", entry.action);
            }
            _ => panic!(
                "decoded kind mismatch for action {}: got {:?}, golden {}",
                entry.action, decoded, entry.decoded.kind
            ),
        }
    }
}

#[test]
fn parity_scoring_samples() {
    let g = load_golden();

    // blankFinishedP0: fixedStart, status=finished, all pieces remaining => -89.
    let mut blank = create_initial_state(StartPolicy::FixedStart);
    blank.status = Status::Finished;
    assert_eq!(score_player(&blank, 0), g.scoring_samples.blank_finished_p0, "blankFinishedP0");
    assert_eq!(g.scoring_samples.blank_finished_p0, -89, "golden blankFinishedP0");

    // allPlacedLastI1: no pieces remaining, last placed I1 => completion+monomino => 20.
    let mut i1 = create_initial_state(StartPolicy::FixedStart);
    i1.remaining_pieces[0] = Vec::new();
    i1.last_placed_piece[0] = Some("I1".to_string());
    assert_eq!(score_player(&i1, 0), g.scoring_samples.all_placed_last_i1, "allPlacedLastI1");
    assert_eq!(g.scoring_samples.all_placed_last_i1, 20, "golden allPlacedLastI1");

    // allPlacedLastI2: no pieces remaining, last placed I2 => completion only => 15.
    let mut i2 = create_initial_state(StartPolicy::FixedStart);
    i2.remaining_pieces[0] = Vec::new();
    i2.last_placed_piece[0] = Some("I2".to_string());
    assert_eq!(score_player(&i2, 0), g.scoring_samples.all_placed_last_i2, "allPlacedLastI2");
    assert_eq!(g.scoring_samples.all_placed_last_i2, 15, "golden allPlacedLastI2");
}

#[test]
fn parity_deterministic_games() {
    let g = load_golden();
    assert!(!g.deterministic_games.is_empty(), "expected deterministic games");

    for game in &g.deterministic_games {
        let policy = parse_policy(&game.start_policy);
        let mut state = create_initial_state(policy);
        let max_plies = 200;
        let mut ply = 0usize;

        for expected in &game.positions {
            assert_eq!(state.status, Status::Playing, "game still playing at ply {}", expected.ply);
            let moves = generate_legal_moves(&state);
            let move_index = (state.turn as usize) % moves.len();
            let mv = &moves[move_index];
            let [score_a, score_b] = score_state(&state);

            // Position-level assertions.
            assert_eq!(ply, expected.ply, "ply index ({})", game.start_policy);
            assert_eq!(state.turn, expected.turn, "turn at ply {}", expected.ply);
            assert_eq!(
                state.current_player, expected.current_player,
                "currentPlayer at ply {}",
                expected.ply
            );
            assert_eq!(
                moves.len(),
                expected.legal_move_count,
                "legalMoveCount at ply {} ({})",
                expected.ply,
                game.start_policy
            );
            assert_eq!(move_index, expected.move_index, "moveIndex at ply {}", expected.ply);
            assert_eq!(
                encode_action(mv),
                expected.selected_action,
                "selectedAction at ply {} ({})",
                expected.ply,
                game.start_policy
            );
            assert_eq!(score_a, expected.score_a, "scoreA at ply {}", expected.ply);
            assert_eq!(score_b, expected.score_b, "scoreB at ply {}", expected.ply);
            assert_eq!(
                sha256_hex(&board_bytes(&state)),
                expected.board_sha,
                "boardSha at ply {} ({})",
                expected.ply,
                game.start_policy
            );
            assert_eq!(
                sha256_hex(&state_bytes(&state, state.current_player)),
                expected.state_sha_current,
                "stateShaCurrent at ply {} ({})",
                expected.ply,
                game.start_policy
            );

            state = apply_move(&state, mv);
            ply += 1;
            assert!(ply <= max_plies, "exceeded max plies");
        }

        assert_eq!(game.positions.len(), game.plies, "plies count ({})", game.start_policy);
        let [final_a, final_b] = score_state(&state);
        assert_eq!(final_a, game.final_score_a, "finalScoreA ({})", game.start_policy);
        assert_eq!(final_b, game.final_score_b, "finalScoreB ({})", game.start_policy);
        assert_eq!(
            sha256_hex(&board_bytes(&state)),
            game.final_board_sha,
            "finalBoardSha ({})",
            game.start_policy
        );
        let expected_status = match game.status.as_str() {
            "finished" => Status::Finished,
            "playing" => Status::Playing,
            other => panic!("unknown status {other}"),
        };
        assert_eq!(state.status, expected_status, "final status ({})", game.start_policy);
    }
}
